version: "3.2"
services:

    rabbitmq:
        container_name: rabbitmq
        image: 'rabbitmq:3'
        restart: always
        ports:
            - 5672
        healthcheck:
            test: rabbitmq-diagnostics -q ping
            interval: 30s
            timeout: 30s
            retries: 3

    receiver:
        container_name: receiver
        image: bryi/helloworldmq
        restart: on-failure
        build:
            context: .
        depends_on:
            - rabbitmq
            - postgres
        environment:
            - PATH=/home/worker/.local/bin:$PATH
        command: python3 -u worker.py

    publisher:
        container_name: publisher
        image: bryi/helloworldmq
        restart: on-failure
        depends_on:
            - receiver
        environment:
            - PATH=/home/worker/.local/bin:$PATH
        command: python3 -u sender.py

    postgres:
        container_name: postgres
        image: 'postgres:12'
        restart: always
        ports:
            - 5432
        #volumes:
        #    - postgres_data:/var/lib/postgresql/data/
        environment:
            - POSTGRES_USER=ctm
            - POSTGRES_PASSWORD=ctm

#volumes:
#    postgres_data:
#        driver: local
